* 1-D Array
* 2-D Array
* 3-D Array
* Higher Dimensional Array

In [3]:
import numpy as np

In [7]:
x = [1,2,3,4]
y = np.array(x)

print("Dimension of Array : ",y.ndim)

Dimension of Array :  1


In [10]:
ar2 = np.array([[1,2,3,4],[9,8,7,6]])
print(ar2)
print("Dimension of Array : ",ar2.ndim)

[[1 2 3 4]
 [9 8 7 6]]
Dimension of Array :  2


In [11]:
ar3 = np.array([[[1,2,3,4],[9,8,7,6],[1,2,3,4]]])
print(ar3)
print("Dimension of Array : ",ar3.ndim)


[[[1 2 3 4]
  [9 8 7 6]
  [1 2 3 4]]]
Dimension of Array :  3


In [13]:
m_ara = np.array([1,2,3,4], ndmin = 5)
print(m_ara)
print("Dimension of Array : ",m_ara.ndim)

[[[[[1 2 3 4]]]]]
Dimension of Array :  5
