In [21]:
import numpy as np

# rand() : generates positive values

In [22]:
x= np.random.rand(4) # this will create 4 random values between 0 and 1
print(x)

[0.82623178 0.79356969 0.07597039 0.5231896 ]


In [23]:
# np.random.rand(D-Dimesnion Array means rows,coloums)
var1 = np.random.rand(2,4) # it generates 2 D arrayof 4 values
print(var1)

[[0.92066482 0.0991212  0.21914454 0.00176859]
 [0.75674321 0.44845859 0.75151065 0.51194089]]


# randn() : generates positive and negatives values closed to 0.


In [24]:
var2 = np.random.randn(5)
print(var2)

[-0.92002171  0.39116014  0.49938899 -1.41694879 -0.50393381]


In [25]:
# np.random.randn(D-Dimension array,coloums)
var3 = np.random.randn(2,5) # 2-D array
print(var3)

[[ 1.37562319 -0.03999757  0.48376913  1.39881212  0.06440573]
 [-0.21515496 -1.14392404  2.03245453 -0.76196423  0.42827283]]


In [26]:
var4 = np.random.randn(3,5) # 3-D array
print(var4)

[[ 1.30174495 -1.23869882  0.22113864  2.88456869  0.0289453 ]
 [ 0.21633659 -0.98719598  0.89434783  0.49519748 -0.84160215]
 [ 0.84306133  1.18422147  0.36641234 -0.15403505  0.1249559 ]]


# randf()

In [36]:
# np.random.ranf('How many numbers means coloum?')
var5 = np.random.ranf(4) # it gives 1-D array
print(var5)

[0.67276997 0.70095894 0.28169365 0.96430698]


# randint

In [35]:
# np.random.randint(min,max,numbers to be generated means coloums)
var6 = np.random.randint(1,10,5)
print(var6)

[2 1 9 2 9]
