In [1]:
import numpy as np

# zeros array(np.zeros)

In [5]:
a_zeros = np.zeros(4)
print(a_zeros)

[0. 0. 0. 0.]


In [31]:
a_zeros1 = np.zeros((3,4))

print(a_zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones filled array (np.ones)

In [40]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [41]:
ar_one1 = np.ones(3)
print(ar_one1)

[1. 1. 1.]


# Empty array (np.empty)

In [42]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# range array (np.arange)

In [43]:
ar_arra = np.arange(4)
print(ar_arra)

[0 1 2 3]


# diagonal array (np.eye)

In [44]:
ar_di = np.eye(3)
print(ar_di)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
ar_di1 = np.eye(5,5)
print(ar_di1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# array having same of spacing among the numbers (np.linspace)

In [46]:
print(np.linspace(0,20, 5))

[ 0.  5. 10. 15. 20.]
