In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
print('Data Type : ', var.dtype)

Data Type :  int32


In [3]:
var = np.array([1.2,2.3,3.0,4])
print('Data Type : ', var.dtype)

Data Type :  float64


In [5]:
var = np.array(['A','a','c',1,23,2])
print('Data Type : ', var.dtype)

Data Type :  <U11


In [6]:
var = np.array(['A','a','c',1,23,2,2.3]) # contains float
print('Data Type : ', var.dtype)

Data Type :  <U32


# changing the data type

In [10]:
x = np.array([1,2,3,4],dtype = np.int8)
print('Data Type : ', x.dtype)

Data Type :  int8


In [11]:
x1 = np.array([1,2,3,4], dtype = 'f')
print('Data Type : ', x1.dtype)

Data Type :  float32


In [14]:
x1 = np.array([1,2,3,4])
print(x1)
print('Data Type : ', x1.dtype)
new = np.float32(x1)
print('Data Type : ',new.dtype)
print(new)

[1 2 3 4]
Data Type :  int32
Data Type :  float32
[1. 2. 3. 4.]


In [15]:
x1 = np.array([1,2,3,4])
print(x1)
print('Data Type : ', x1.dtype)
new = np.float32(x1)
new_1 = np.int_(new)
print('Data Type : ',new.dtype)
print(new)
print(new_1)
print('Data Type : ',new_1.dtype)

[1 2 3 4]
Data Type :  int32
Data Type :  float32
[1. 2. 3. 4.]
[1 2 3 4]
Data Type :  int32


In [19]:
x1 = np.array([1,2,3,4])
new1 = x1.astype(float)
print(x1.dtype)
print(new1.dtype)

int32
float64
