In [1]:
import numpy as np

# Addition

In [2]:
var  = np.array([1,2,3,4])
var_add = var + 3
print(var_add) 

[4 5 6 7]


In [4]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_added = var + var2
print(var_added)

[5 5 5 5]


# Subtraction

In [10]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_sub = var - var2
print(var_sub)

[-3 -1  1  3]


# Multiplication

In [11]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_mul = var * var2
print(var_mul)

[4 6 6 4]


# Division

In [12]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_div = var / var2
print(var_div)

[0.25       0.66666667 1.5        4.        ]


# Modulus

In [13]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_mod = var % var2
print(var_mod)

[1 2 1 0]


# power

In [27]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_pow = var ** var2
print(var_pow)

[1 8 9 4]


# reciprocal

In [30]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_reci = 1/var  

print(var_reci)

[1.         0.5        0.33333333 0.25      ]


# functions for above all

In [16]:
var  = np.array([1,2,3,4])
var_add = np.add(var , 3)
print(var_add)

[4 5 6 7]


In [14]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_added = np.add(var, var2)
print(var_added)

[5 5 5 5]


In [19]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_sub = np.subtract(var , var2)
print(var_sub)

[-3 -1  1  3]


In [20]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_mul = np.multiply(var , var2)
print(var_mul)

[4 6 6 4]


In [21]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_div = np.divide(var , var2)
print(var_div)

[0.25       0.66666667 1.5        4.        ]


In [22]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_mod = np.mod(var , var2)
print(var_mod)

[1 2 1 0]


In [24]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_pow = np.power(var , var2)
print(var_pow)

[1 8 9 4]


In [29]:
var  = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])
var_reci = np.reciprocal(var )
print(var_reci)

[1 0 0 0]


# 2D dimension

In [34]:
var  = np.array([[1,2,3,4],[2,3,4,5]])
var2 = np.array([[4,3,2,1],[1,2,3,4]])
dvar_add = np.add(var,var2)
print(dvar_add)

[[5 5 5 5]
 [3 5 7 9]]


In [35]:
var  = np.array([[1,2,3,4],[2,3,4,5]])
var2 = np.array([[4,3,2,1],[1,2,3,4]])
dvar_mul = np.multiply(var,var2)
print(dvar_mul)

[[ 4  6  6  4]
 [ 2  6 12 20]]
