np.min <br>
np.max <br>
np.argmin <br>
np.argmax <br>
np.sqrt <br>
np.sin <br>
np.cos <br>
np.cumsum <br>

In [1]:
import numpy as np

In [10]:
var = np.array([1,2,3,4,3,5,2])
print('min :',np.min(var),np.argmin(var)) # np.argmin gives us the location of the min value
print('max :',np.max(var),np.argmax(var))
print('sqrt :', np.sqrt(var))

min : 1 0
max : 5 5
sqrt : [1.         1.41421356 1.73205081 2.         1.73205081 2.23606798
 1.41421356]


In [9]:
var1 = np.array([[4,3,2,5], [5,4,7,5]])
print(np.min(var1, axis = 1))  # This is for row, x-axis the value would be 1
print(np.min(var1, axis = 0))  # This is for coloum, x-axis the value would be 0

[2 4]
[4 3 2 5]


In [18]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [17]:
print(np.cos(0))

1.0
