var_name.shape : it gives us the details of the rows and coloums <br>
var_name.reshape : it shapes the array into the desired array

In [2]:
import numpy as np

In [38]:
var = np.array([[1,2] ,[1,2]])
print(var)
print('Dim of Array : ', var.shape)


[[1 2]
 [1 2]]
Dim of Array :  (2, 2)


In [39]:
var = np.array([[1,2,3,4] ,[1,2,5,6]])
print(var)
print('Dim of Array : ', var.shape)

[[1 2 3 4]
 [1 2 5 6]]
Dim of Array :  (2, 4)


In [40]:
var = np.array([1,2,3,4],ndmin = 5)
print(var)
print('Dim of Array : ', var.shape)
                

[[[[[1 2 3 4]]]]]
Dim of Array :  (1, 1, 1, 1, 4)


# Reshaping

In [41]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print('Dim of Array :',var2.ndim)
x = var2.reshape(2,3)
print(x)
print('Dim of Array :',x.ndim)

[1 2 3 4 5 6]
Dim of Array : 1
[[1 2 3]
 [4 5 6]]
Dim of Array : 2


In [42]:
# 3D array

In [4]:
var3 = np.array([1,2,3,4,5,6,7,8,9])
print(var3)
print('Dim of Array :',var3.ndim)
x = var3.reshape(1,3,3)
print(x)
print('Dim of Array :',x.ndim) 

[1 2 3 4 5 6 7 8 9]
Dim of Array : 1
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dim of Array : 3


In [44]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print('Dim of Array :',var3.ndim)
x = var3.reshape(2,3,2)
print(x)
print('Dim of Array :',x.ndim) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of Array : 1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dim of Array : 3


In [45]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print('Dim of Array :',var3.ndim)
x = var3.reshape(2,3,2)
print(x)
print('Dim of Array :',x.ndim) 
one = x.reshape(2,6)
print(one)
print('Dim of Array :',one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of Array : 1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dim of Array : 3
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Dim of Array : 2


In [46]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print('Dim of Array :',var3.ndim)
x = var3.reshape(2,3,2)
print(x)
print('Dim of Array :',x.ndim) 
one = x.reshape(-1)
print(one)
print('Dim of Array :',one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of Array : 1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dim of Array : 3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dim of Array : 1
