In [2]:
import numpy as np

In [11]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3])

print(var + var1)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [13]:
var = np.array([1,2,3])
print(var)
print("shape of array",var.shape)
print()
var1 = np.array([[1],[2],[3]])
print(var1)
print("shape of array",var1.shape)
print()
print(var + var1)


[1 2 3]
shape of array (3,)

[[1]
 [2]
 [3]]
shape of array (3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
