# Indexing

In [4]:
import numpy as np

In [6]:
var = np.array([1,2,3,4]) # same as list
print(var[1])
print(var[3])
print(var[-1])
    

2
4
4


In [10]:
var = np.array([[1,2,3,4],[9,8,7,6]])
print(var[0,1]) # to get 2 in the frist list
print(var[1,2]) # to get 7 in the frist list

2
7


In [13]:
var = np.array([[[1,2,3,4],[9,8,7,6]]])
# print(var.ndim)
print(var[0,1,2]) # to get 7 in the second array
print(var[0,0,2])

7
3


# Slicing

In [20]:
var = np.array([1,2,3,4,5,6,7]) # same as list
print(var[1:4]) # giving start and stop
print(var[1:])
print(var[:4])
print(var[1:6:2]) # giving start and stop as well jump
print(var[::2])

[2 3 4]
[2 3 4 5 6 7]
[1 2 3 4]
[2 4 6]
[1 3 5 7]


In [26]:
var = np.array([[1,2,3,4,6,7],[9,8,7,6,2,3]])
print(var[1,1:])
print(var[1,1:3])
print(var[1,:3])
print(var[1,:3:2]) # giving steps as well

[8 7 6 2 3]
[8 7]
[9 8 7]
[9 7]


In [29]:
var = np.array([[[1,2,3,4,6,7],[9,8,7,6,2,3]]])
# print(var.ndim)
print(var[0,1,2:]) # to get 7 in the second array
print(var[0,1,:5])
print(var[0,1,1::2])
# print(var[0,0,2])

[7 6 2 3]
[9 8 7 6 2]
[8 6 3]
