copy
view
basic diffence between them is. if we change the original data in the copy function we willl not see that changes but in the view we will

In [2]:
import numpy as np

In [6]:
var = np.array([1,2,3,4])

ca = var.copy()
var[2] = 45
print(var)
print(ca)

[ 1  2 45  4]
[1 2 3 4]


In [7]:
var = np.array([1,2,3,4])

vi = var.view()
var[2] = 45
print(var)
print(vi)

[ 1  2 45  4]
[ 1  2 45  4]
