np.concatenate <br>
np.stack <br>
np.split

In [16]:
import numpy as np

In [17]:
var = np.array([1,2,3,4]) # 1D array
var1 = np.array([1,2,3,4])
var2 = np.concatenate((var,var1))
print(var2)

[1 2 3 4 1 2 3 4]


In [25]:
var = np.array([[2,2,2,4],[1,2,3,4]]) # 2D array
var1 = np.array([[7,4,3,4],[1,2,3,4]])
var2 = np.concatenate((var,var1),axis = 1) # the arrays are merge in x-axis
print(var2)

[[2 2 2 4 7 4 3 4]
 [1 2 3 4 1 2 3 4]]


In [7]:
var = np.array([[2,2,2,4],[1,2,3,4]]) # 2D array
var1 = np.array([[7,4,3,4],[1,2,3,4]])
var2 = np.concatenate((var,var1),axis = 0) # the arrays are merge in y-axis
print(var2)

[[2 2 2 4]
 [1 2 3 4]
 [7 4 3 4]
 [1 2 3 4]]


In [23]:
var = np.array([1,2,3,4]) # 1D array
var1 = np.array([1,2,3,4])
var2 = np.stack((var,var1),axis = 0) # this is oppisite of the concatenate here 0 means x-axis and 1 means y-axis
var3 = np.hstack((var,var1)) # row
var4 = np.vstack((var,var1)) # coloum
var5 = np.dstack((var,var1)) # height
print(var2)
print()
print(var3)
print()
print(var4)
print()
print(var5)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4 1 2 3 4]

[[1 2 3 4]
 [1 2 3 4]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]]]


# Splitting

In [29]:
var = np.array([1,2,3,4,6,7]) # 1D array
print(var)
var1 = np.array_split(var,3) # Give number that how many array do you wnat
print(var1)

[1 2 3 4 6 7]
[array([1, 2]), array([3, 4]), array([6, 7])]


In [30]:
var = np.array([[1,2],[3,4],[6,7]]) # 2D array
print(var)
var1 = np.array_split(var,3) # Give number that how many array do you wnat
print(var1)

[[1 2]
 [3 4]
 [6 7]]
[array([[1, 2]]), array([[3, 4]]), array([[6, 7]])]


In [31]:
var = np.array([[1,2],[3,4],[6,7]]) # 2D array
print(var)
var1 = np.array_split(var,3,axis = 1) # Give number that how many array do you wnat
print(var1)

[[1 2]
 [3 4]
 [6 7]]
[array([[1],
       [3],
       [6]]), array([[2],
       [4],
       [7]]), array([], shape=(3, 0), dtype=int32)]
