np.where : to find the location of the elements <br>
np.searchsorted : to gives the details of the input number where to put <br>
np.sort : <br>
filter <br>
np.random.shuffle() : it change the order of the array<br>
np.unique() : it gives unique values of the array<br>
.flatten() : it converts the 2D array into 1D array <br>
.ravel()

In [1]:
import numpy as np

where()

In [3]:
var = np.array([1,2,3,4,5,3,2,4,5])
x = np.where( var == 2) 
print(x)


(array([1, 6], dtype=int64),)


searchsorted ()

In [6]:
var = np.array([1,2,3,4,5,3,2,4,5])
x = np.searchsorted( var , 5) # it is normallly used for sorted array
y = np.searchsorted( var , 3, side = 'right')
print(x)
print(y)

4
3


sort()

In [8]:
var = np.array([1,2,3,4,5,7,6,9,8])
print(np.sort(var))

[1 2 3 4 5 6 7 8 9]


In [9]:
var = np.array([[1,3,2,4,5],[7,6,9,8]])
print(np.sort(var))

[list([1, 3, 2, 4, 5]) list([7, 6, 9, 8])]


C:\Users\Danya\AppData\Local\Temp\ipykernel_16136\2525205286.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  var = np.array([[1,3,2,4,5],[7,6,9,8]])


filter array  

In [11]:
var = np.array([1,2,3,4])
f  = [True, False, True,False]

new = var[f]

print(var)
print(new)

[1 2 3 4]
[1 3]


shuffle()

In [12]:
var = np.array([1,2,3,4])
np.random.shuffle(var)
print(var)

[2 3 1 4]


unique()

In [15]:
var = np.array([1,2,3,4,3,7,8,3])
x = np.unique(var, return_index = True, return_counts = True)
print(x)

(array([1, 2, 3, 4, 7, 8]), array([0, 1, 2, 3, 5, 6], dtype=int64), array([1, 1, 3, 1, 1, 1], dtype=int64))


resize()

In [18]:
var = np.array([1,2,3,4,3,7,8,3])
print(var)
y = np.resize(var,(2,3))
y1 = np.resize(var,(2,3))
print(y)
print(y1)

[1 2 3 4 3 7 8 3]
[[1 2 3]
 [4 3 7]]
[[1 2 3]
 [4 3 7]]


faltten() and ravel()

In [25]:
var = np.array([1,2,3,4,3,7,8,3])
print(var)
y = np.resize(var,(2,3))
print()
print(y)
print()
print(y.flatten()) # we can change the order of the flatten
print()
print(np.ravel(y, order = 'F')) # we can change the order of the flatten


[1 2 3 4 3 7 8 3]

[[1 2 3]
 [4 3 7]]

[1 2 3 4 3 7]

[1 4 2 3 3 7]
