In [1]:
import numpy as np

In [2]:
# insert

In [11]:
var = np.array([1,2,3,4,5])
print(var)
# print(type(var))
v = np.insert(var, 2 , 40) # np.insert(var_name, index, value)
print(v)
v = np.insert(var, (2,5) , 40) # we can give multiple index, float value will be convert into int
print(v)

[1 2 3 4 5]
[ 1  2 40  3  4  5]
[ 1  2 40  3  4  5 40]


In [16]:
var = np.array([[1,2,3],[4,5,6]])
print(var)
v = np.insert(var, 2, 6 ,axis = 0)  # we need to give axis as well.
print(v)
v1 = np.insert(var, 2, 6 ,axis = 1)  # we need to give axis as well.
print(v1)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [6 6 6]]
[[1 2 6 3]
 [4 5 6 6]]


Delete()


In [21]:
var = np.array([1,2,3,4,5])
print(var)

d = np.delete(var,3) # it will delete value of index 3
print(d)

[1 2 3 4 5]
[1 2 3 5]
