* Addition
* Subtraction
* Mutliplication
* np.transpose()
* np.swapaxes()

In [1]:
import numpy as np

In [15]:
var = np.array([[1,2,3,4],[4,3,2,1]])
print(var)
print(type(var))

[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.ndarray'>


# addition

In [16]:
var1 = np.matrix([[1,2,3,4],[4,3,2,1]])
var2 = np.matrix([[1,2,3,4],[4,3,2,1]])
print(var1)
print(type(var1))
print(var1 + var2)

[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.matrix'>
[[2 4 6 8]
 [8 6 4 2]]


In [17]:
# Subtraction

In [20]:
var1 = np.matrix([[1,2,3,4],[4,5,2,1]])
var2 = np.matrix([[1,8,9,4],[4,3,2,1]])
print(var1)
print(type(var1))
print(var1 -var2)

[[1 2 3 4]
 [4 5 2 1]]
<class 'numpy.matrix'>
[[ 0 -6 -6  0]
 [ 0  2  0  0]]


In [21]:
# Multiplication : number of rows must be equall to number of coloum

In [27]:
var1 = np.matrix([[1,2],[4,3]])
var2 = np.matrix([[1,2,],[3,4]])
print(var1)
print(type(var1))
print(var1 * var2)
print()
print(var1.dot (var2))
print()
print(var1.dot(var1))

[[1 2]
 [4 3]]
<class 'numpy.matrix'>
[[ 7 10]
 [13 20]]

[[ 7 10]
 [13 20]]

[[ 9  8]
 [16 17]]


# Matrix Function

In [28]:
# Transpose

In [31]:
var = np.matrix([[1,2,3],[4,3,5]])
print(var)
print()
print(np.transpose(var)) # taking transpose via np fucntion
print()
print(var.T) # this is another way to take transpose 

[[1 2 3]
 [4 3 5]]

[[1 4]
 [2 3]
 [3 5]]

[[1 4]
 [2 3]
 [3 5]]


In [33]:
# swapaxis : Similar to the Transpose

In [38]:
var = np.matrix([[1,2,3],[4,3,5]])
print(var)
print()
print(np.swapaxes(var,0,1)) # (var_name , x-axis, y-axis)

[[1 2 3]
 [4 3 5]]

[[1 4]
 [2 3]
 [3 5]]


In [39]:
# inverse

In [46]:
var = np.matrix([[1,2],[4,3]])
print(var)
print()
print(np.linalg.inv(var)) # this functon is useedd for taking inverse|

[[1 2]
 [4 3]]

[[-0.6  0.4]
 [ 0.8 -0.2]]


In [47]:
# power

In [51]:
var = np.matrix([[1,2],[4,3]])
print(var)
print()
# different taking power(var_name, power to be taken)
print(np.linalg.matrix_power(var,2))
print()

print(np.linalg.matrix_power(var,0))

print()

print(np.linalg.matrix_power(var,-2))

[[1 2]
 [4 3]]

[[ 9  8]
 [16 17]]

[[1 0]
 [0 1]]

[[ 0.68 -0.32]
 [-0.64  0.36]]


In [52]:
# determinate

In [53]:
var = np.matrix([[1,2],[4,3]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [4 3]]

-4.999999999999999
